[package]
name = "simple_scrapping_rust"
version = "0.1.0"
edition = "2021"
[dependencies]
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
scraper = "0.15"
tokio = { version = "1", features = ["full"] }